Repository PX4/PX4-SITL_gazebo, pull requests merged in 2020-05, with the labels that each got.

#485 Fix wind velocity transformation
  src/gazebo_mavlink_interface.cpp
Labels: bug

#502 Travis CI: add pipelines to build and test with Gazebo 11 over Ubuntu 20.04
  .travis.yml
Labels: CI, enhancement

#507 CI: bump container tags to 2020-05-28; temporarly remove Gazebo 11 and Kinetic builds
  .travis.yml
Labels: CI
